[versions]
kotlin = "2.1.20"
freemarker = "2.3.34"
mavenPublish = "0.31.0"
npmPublish = "4.0.2"

[libraries]
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }

# Gradle plugins
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
mavenPublish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "mavenPublish" }

[plugins]
npmPublish = { id = "org.danilopianini.npm.publish", version.ref = "npmPublish" }
