name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Cache Konan files
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Run build
        run: ./gradlew clean build
        working-directory: ${{ github.workspace }}
